language: php
php:
    - 5.6
before_script:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - composer install
script:
    - bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
    - bin/coveralls -v
