<?php

namespace PTS\UserRegistrationBundle\Entity;

/**
 * UserHashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHashRepository extends \Doctrine\ORM\EntityRepository
{
    public function newUserHash()
    {
        return new UserHash();
    }
}
