<?php

namespace PTS\UserRegistrationBundle\Entity;

use PTS\UserRegistrationBundle\Util;

/**
 * UserHashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHashRepository extends \Doctrine\ORM\EntityRepository
{
    public function newUserHash()
    {
        return new UserHash();
    }

    /**
     * @return string
     */
    public function generateNewValue()
    {
        return sprintf('%s-%s', Util::uuidv4(), Util::uuidv4());
    }
}
